package org.czy.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.czy.entity.Qcdb;

public interface QcdbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    int insert(Qcdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    int insertSelective(Qcdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    Qcdb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Qcdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qcdb
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Qcdb record);
    
    List<Qcdb> selectAll();
    
    Qcdb selectByName(String dbname);
    
    Qcdb selectByIP(@Param("ip")String ip,@Param("dbname")String dbname);
}