package org.czy.dao;

import java.util.List;

import org.czy.entity.ServerCount;

public interface ServerCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    int insert(ServerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    int insertSelective(ServerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    ServerCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServerCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servercount
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServerCount record);
    
    
    List<ServerCount> selectByAll();
    
    List<ServerCount> selectByCount();
}