package org.czy.dao;

import java.util.List;

import org.czy.entity.Switcham;

public interface SwitchamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    int insert(Switcham record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    int insertSelective(Switcham record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    Switcham selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Switcham record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switcham
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Switcham record);
    
    List<Switcham> selectAllByQID(Integer qid);
}