package org.czy.dao;

import java.util.List;

import org.czy.entity.Train;

public interface TrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int insert(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int insertSelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    Train selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Train record);
    
    
    Train selectByTitle(String title);
    
    List<Train> selectByAll();
    
    List<Train> selectByTopTimeDesc(Integer num);
    
    int selectByCount();
}