package org.czy.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ServerCount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.countTime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date counttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.ppCount
     *
     * @mbg.generated
     */
    private String ppcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.apiCount
     *
     * @mbg.generated
     */
    private Integer apicount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.addTest
     *
     * @mbg.generated
     */
    private Integer addtest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.upTool
     *
     * @mbg.generated
     */
    private Integer uptool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.runTest
     *
     * @mbg.generated
     */
    private Integer runtest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.useTool
     *
     * @mbg.generated
     */
    private Integer usetool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.activeProject
     *
     * @mbg.generated
     */
    private String activeproject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.updateTest
     *
     * @mbg.generated
     */
    private String updatetest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.regresscount
     *
     * @mbg.generated
     */
    private Integer regresscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servercount.releasecount
     *
     * @mbg.generated
     */
    private Integer releasecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.id
     *
     * @return the value of servercount.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.id
     *
     * @param id the value for servercount.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.countTime
     *
     * @return the value of servercount.countTime
     *
     * @mbg.generated
     */
    public Date getCounttime() {
        return counttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.countTime
     *
     * @param counttime the value for servercount.countTime
     *
     * @mbg.generated
     */
    public void setCounttime(Date counttime) {
        this.counttime = counttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.ppCount
     *
     * @return the value of servercount.ppCount
     *
     * @mbg.generated
     */
    public String getPpcount() {
        return ppcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.ppCount
     *
     * @param ppcount the value for servercount.ppCount
     *
     * @mbg.generated
     */
    public void setPpcount(String ppcount) {
        this.ppcount = ppcount == null ? null : ppcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.apiCount
     *
     * @return the value of servercount.apiCount
     *
     * @mbg.generated
     */
    public Integer getApicount() {
        return apicount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.apiCount
     *
     * @param apicount the value for servercount.apiCount
     *
     * @mbg.generated
     */
    public void setApicount(Integer apicount) {
        this.apicount = apicount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.addTest
     *
     * @return the value of servercount.addTest
     *
     * @mbg.generated
     */
    public Integer getAddtest() {
        return addtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.addTest
     *
     * @param addtest the value for servercount.addTest
     *
     * @mbg.generated
     */
    public void setAddtest(Integer addtest) {
        this.addtest = addtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.upTool
     *
     * @return the value of servercount.upTool
     *
     * @mbg.generated
     */
    public Integer getUptool() {
        return uptool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.upTool
     *
     * @param uptool the value for servercount.upTool
     *
     * @mbg.generated
     */
    public void setUptool(Integer uptool) {
        this.uptool = uptool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.runTest
     *
     * @return the value of servercount.runTest
     *
     * @mbg.generated
     */
    public Integer getRuntest() {
        return runtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.runTest
     *
     * @param runtest the value for servercount.runTest
     *
     * @mbg.generated
     */
    public void setRuntest(Integer runtest) {
        this.runtest = runtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.useTool
     *
     * @return the value of servercount.useTool
     *
     * @mbg.generated
     */
    public Integer getUsetool() {
        return usetool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.useTool
     *
     * @param usetool the value for servercount.useTool
     *
     * @mbg.generated
     */
    public void setUsetool(Integer usetool) {
        this.usetool = usetool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.activeProject
     *
     * @return the value of servercount.activeProject
     *
     * @mbg.generated
     */
    public String getActiveproject() {
        return activeproject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.activeProject
     *
     * @param activeproject the value for servercount.activeProject
     *
     * @mbg.generated
     */
    public void setActiveproject(String activeproject) {
        this.activeproject = activeproject == null ? null : activeproject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.updateTest
     *
     * @return the value of servercount.updateTest
     *
     * @mbg.generated
     */
    public String getUpdatetest() {
        return updatetest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.updateTest
     *
     * @param updatetest the value for servercount.updateTest
     *
     * @mbg.generated
     */
    public void setUpdatetest(String updatetest) {
        this.updatetest = updatetest == null ? null : updatetest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.regresscount
     *
     * @return the value of servercount.regresscount
     *
     * @mbg.generated
     */
    public Integer getRegresscount() {
        return regresscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.regresscount
     *
     * @param regresscount the value for servercount.regresscount
     *
     * @mbg.generated
     */
    public void setRegresscount(Integer regresscount) {
        this.regresscount = regresscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servercount.releasecount
     *
     * @return the value of servercount.releasecount
     *
     * @mbg.generated
     */
    public Integer getReleasecount() {
        return releasecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servercount.releasecount
     *
     * @param releasecount the value for servercount.releasecount
     *
     * @mbg.generated
     */
    public void setReleasecount(Integer releasecount) {
        this.releasecount = releasecount;
    }
}