package org.czy.dao;

import java.util.List;

import org.czy.entity.Description;

public interface DescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    int deleteByTestID(Integer testID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    int insert(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    int insertSelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    List<Description> selectByTestID(Integer testID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Description record);
    
    int deleteByPrimaryKey(Integer id);
    
    List<String> selectNameByTestID(Integer testID);
    
    int selectCountByTestID(Integer testID);
    
}