package org.czy.dao;

import java.util.List;

import org.czy.entity.WorkDynamic;

public interface WorkDynamicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    int insert(WorkDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    int insertSelective(WorkDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    WorkDynamic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkDynamic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workdynamic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkDynamic record);
    
    WorkDynamic selectByTitle(String title);
    
    List<WorkDynamic> selectByAll();
    
    List<WorkDynamic> selectByTopTimeDesc(Integer num);
    
    int selCount();
}