package org.czy.entity;

public class Description {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.name
     *
     * @mbg.generated
     */
    private String name;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.resultDescription
     *
     * @mbg.generated
     */
    private String resultdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.resultType
     *
     * @mbg.generated
     */
    private String resulttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.resultName
     *
     * @mbg.generated
     */
    private String resultname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column description.testID
     *
     * @mbg.generated
     */
    private Integer testid;
    
    
    
    private Integer step;

    public Integer getStep() {
		return step;
	}

	public void setStep(Integer step) {
		this.step = step;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.id
     *
     * @return the value of description.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.id
     *
     * @param id the value for description.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.name
     *
     * @return the value of description.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.name
     *
     * @param name the value for description.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.type
     *
     * @return the value of description.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.type
     *
     * @param type the value for description.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.Description
     *
     * @return the value of description.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.Description
     *
     * @param description the value for description.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.resultDescription
     *
     * @return the value of description.resultDescription
     *
     * @mbg.generated
     */
    public String getResultdescription() {
        return resultdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.resultDescription
     *
     * @param resultdescription the value for description.resultDescription
     *
     * @mbg.generated
     */
    public void setResultdescription(String resultdescription) {
        this.resultdescription = resultdescription == null ? null : resultdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.resultType
     *
     * @return the value of description.resultType
     *
     * @mbg.generated
     */
    public String getResulttype() {
        return resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.resultType
     *
     * @param resulttype the value for description.resultType
     *
     * @mbg.generated
     */
    public void setResulttype(String resulttype) {
        this.resulttype = resulttype == null ? null : resulttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.resultName
     *
     * @return the value of description.resultName
     *
     * @mbg.generated
     */
    public String getResultname() {
        return resultname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.resultName
     *
     * @param resultname the value for description.resultName
     *
     * @mbg.generated
     */
    public void setResultname(String resultname) {
        this.resultname = resultname == null ? null : resultname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column description.testID
     *
     * @return the value of description.testID
     *
     * @mbg.generated
     */
    public Integer getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column description.testID
     *
     * @param testid the value for description.testID
     *
     * @mbg.generated
     */
    public void setTestid(Integer testid) {
        this.testid = testid;
    }
}