package org.czy.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class RecordExec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.redmineNo
     *
     * @mbg.generated
     */
    private String redmineno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.qcdbID
     *
     * @mbg.generated
     */
    private String qcdbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.userNo
     *
     * @mbg.generated
     */
    private String userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.execdate
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date execdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.execTime
     *
     * @mbg.generated
     */
    private String exectime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.testCount
     *
     * @mbg.generated
     */
    private Integer testcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.success
     *
     * @mbg.generated
     */
    private Integer success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.fail
     *
     * @mbg.generated
     */
    private Integer fail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recordexec.succesRate
     *
     * @mbg.generated
     */
    private String succesrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.id
     *
     * @return the value of recordexec.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.id
     *
     * @param id the value for recordexec.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.redmineNo
     *
     * @return the value of recordexec.redmineNo
     *
     * @mbg.generated
     */
    public String getRedmineno() {
        return redmineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.redmineNo
     *
     * @param redmineno the value for recordexec.redmineNo
     *
     * @mbg.generated
     */
    public void setRedmineno(String redmineno) {
        this.redmineno = redmineno == null ? null : redmineno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.qcdbID
     *
     * @return the value of recordexec.qcdbID
     *
     * @mbg.generated
     */
    public String getQcdbid() {
        return qcdbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.qcdbID
     *
     * @param qcdbid the value for recordexec.qcdbID
     *
     * @mbg.generated
     */
    public void setQcdbid(String qcdbid) {
        this.qcdbid = qcdbid == null ? null : qcdbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.userNo
     *
     * @return the value of recordexec.userNo
     *
     * @mbg.generated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.userNo
     *
     * @param userno the value for recordexec.userNo
     *
     * @mbg.generated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.execdate
     *
     * @return the value of recordexec.execdate
     *
     * @mbg.generated
     */
    public Date getExecdate() {
        return execdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.execdate
     *
     * @param execdate the value for recordexec.execdate
     *
     * @mbg.generated
     */
    public void setExecdate(Date execdate) {
        this.execdate = execdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.execTime
     *
     * @return the value of recordexec.execTime
     *
     * @mbg.generated
     */
    public String getExectime() {
        return exectime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.execTime
     *
     * @param exectime the value for recordexec.execTime
     *
     * @mbg.generated
     */
    public void setExectime(String exectime) {
        this.exectime = exectime == null ? null : exectime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.testCount
     *
     * @return the value of recordexec.testCount
     *
     * @mbg.generated
     */
    public Integer getTestcount() {
        return testcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.testCount
     *
     * @param testcount the value for recordexec.testCount
     *
     * @mbg.generated
     */
    public void setTestcount(Integer testcount) {
        this.testcount = testcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.success
     *
     * @return the value of recordexec.success
     *
     * @mbg.generated
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.success
     *
     * @param success the value for recordexec.success
     *
     * @mbg.generated
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.fail
     *
     * @return the value of recordexec.fail
     *
     * @mbg.generated
     */
    public Integer getFail() {
        return fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.fail
     *
     * @param fail the value for recordexec.fail
     *
     * @mbg.generated
     */
    public void setFail(Integer fail) {
        this.fail = fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recordexec.succesRate
     *
     * @return the value of recordexec.succesRate
     *
     * @mbg.generated
     */
    public String getSuccesrate() {
        return succesrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recordexec.succesRate
     *
     * @param succesrate the value for recordexec.succesRate
     *
     * @mbg.generated
     */
    public void setSuccesrate(String succesrate) {
        this.succesrate = succesrate == null ? null : succesrate.trim();
    }
}