package org.czy.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Tools {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.toolClass
     *
     * @mbg.generated
     */
    private Integer toolclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.useCount
     *
     * @mbg.generated
     */
    private Integer usecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.downloadCount
     *
     * @mbg.generated
     */
    private Integer downloadcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.uploadtime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date uploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.uploaduid
     *
     * @mbg.generated
     */
    private Integer uploaduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.studyurl
     *
     * @mbg.generated
     */
    private String studyurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tools.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.id
     *
     * @return the value of tools.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.id
     *
     * @param id the value for tools.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.type
     *
     * @return the value of tools.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.type
     *
     * @param type the value for tools.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.toolClass
     *
     * @return the value of tools.toolClass
     *
     * @mbg.generated
     */
    public Integer getToolclass() {
        return toolclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.toolClass
     *
     * @param toolclass the value for tools.toolClass
     *
     * @mbg.generated
     */
    public void setToolclass(Integer toolclass) {
        this.toolclass = toolclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.useCount
     *
     * @return the value of tools.useCount
     *
     * @mbg.generated
     */
    public Integer getUsecount() {
        return usecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.useCount
     *
     * @param usecount the value for tools.useCount
     *
     * @mbg.generated
     */
    public void setUsecount(Integer usecount) {
        this.usecount = usecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.downloadCount
     *
     * @return the value of tools.downloadCount
     *
     * @mbg.generated
     */
    public Integer getDownloadcount() {
        return downloadcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.downloadCount
     *
     * @param downloadcount the value for tools.downloadCount
     *
     * @mbg.generated
     */
    public void setDownloadcount(Integer downloadcount) {
        this.downloadcount = downloadcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.uploadtime
     *
     * @return the value of tools.uploadtime
     *
     * @mbg.generated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.uploadtime
     *
     * @param uploadtime the value for tools.uploadtime
     *
     * @mbg.generated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.uploaduid
     *
     * @return the value of tools.uploaduid
     *
     * @mbg.generated
     */
    public Integer getUploaduid() {
        return uploaduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.uploaduid
     *
     * @param uploaduid the value for tools.uploaduid
     *
     * @mbg.generated
     */
    public void setUploaduid(Integer uploaduid) {
        this.uploaduid = uploaduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.studyurl
     *
     * @return the value of tools.studyurl
     *
     * @mbg.generated
     */
    public String getStudyurl() {
        return studyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.studyurl
     *
     * @param studyurl the value for tools.studyurl
     *
     * @mbg.generated
     */
    public void setStudyurl(String studyurl) {
        this.studyurl = studyurl == null ? null : studyurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.url
     *
     * @return the value of tools.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.url
     *
     * @param url the value for tools.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tools.name
     *
     * @return the value of tools.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tools.name
     *
     * @param name the value for tools.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}