package org.czy.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class WorkDynamic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workdynamic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workdynamic.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workdynamic.time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workdynamic.cid
     * 发布人
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workdynamic.temp
     * 内容
     * @mbg.generated
     */
    private String temp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workdynamic.id
     *
     * @return the value of workdynamic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workdynamic.id
     *
     * @param id the value for workdynamic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workdynamic.title
     *
     * @return the value of workdynamic.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workdynamic.title
     *
     * @param title the value for workdynamic.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workdynamic.time
     *
     * @return the value of workdynamic.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workdynamic.time
     *
     * @param time the value for workdynamic.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workdynamic.cid
     *
     * @return the value of workdynamic.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workdynamic.cid
     *
     * @param cid the value for workdynamic.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workdynamic.temp
     *
     * @return the value of workdynamic.temp
     *
     * @mbg.generated
     */
    public String getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workdynamic.temp
     *
     * @param temp the value for workdynamic.temp
     *
     * @mbg.generated
     */
    public void setTemp(String temp) {
        this.temp = temp == null ? null : temp.trim();
    }
}