package org.czy.entity;

public class Qcdb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.dbname
     *
     * @mbg.generated
     */
    private String dbname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qcdb.projectid
     *
     * @mbg.generated
     */
    private String projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.id
     *
     * @return the value of qcdb.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.id
     *
     * @param id the value for qcdb.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.dbname
     *
     * @return the value of qcdb.dbname
     *
     * @mbg.generated
     */
    public String getDbname() {
        return dbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.dbname
     *
     * @param dbname the value for qcdb.dbname
     *
     * @mbg.generated
     */
    public void setDbname(String dbname) {
        this.dbname = dbname == null ? null : dbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.ip
     *
     * @return the value of qcdb.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.ip
     *
     * @param ip the value for qcdb.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.username
     *
     * @return the value of qcdb.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.username
     *
     * @param username the value for qcdb.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.password
     *
     * @return the value of qcdb.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.password
     *
     * @param password the value for qcdb.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qcdb.projectid
     *
     * @return the value of qcdb.projectid
     *
     * @mbg.generated
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qcdb.projectid
     *
     * @param projectid the value for qcdb.projectid
     *
     * @mbg.generated
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }
}